name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: vendor/bin/phpunit

    - name: Process Code Coverage
      run: COVERALLS_RUN_LOCALLY=true COVERALLS_REPO_TOKEN=meh php vendor/bin/php-coveralls --dry-run --coverage_clover=./build/logs/clover.xml --json_path=./build/logs/lcov.info

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./build/logs/lcov.info
